# Generated by Django 4.1.3 on 2022-12-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_guest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
