# Generated by Django 4.1.3 on 2022-12-30 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.GUEST_USER_MODEL),
        ("skincure", "0006_result_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="guest",
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guest",
                to=settings.GUEST_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
