# Generated by Django 4.1.3 on 2023-01-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skincure", "0010_rename_user_profile_guest_rename_user_result_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="sex",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
