# Generated by Django 4.1.3 on 2023-01-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skincure", "0011_profile_sex"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="age",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="sex",
        ),
        migrations.AddField(
            model_name="result",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="result",
            name="name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="result",
            name="sex",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
